import * as Icons from "@ant-design/icons";
import { IconsStyleType } from "../index.d"

const linear: IconsStyleType = {
  name: 'linear',
  items: [
    {
      name: 'direction',
      items: [
        { name: 'StepBackwardOutlined', value: <Icons.StepBackwardOutlined /> },
        { name: 'StepForwardOutlined', value: <Icons.StepForwardOutlined /> },
        { name: 'FastBackwardOutlined', value: <Icons.FastBackwardOutlined /> },
        { name: 'FastForwardOutlined', value: <Icons.FastForwardOutlined /> },
        { name: 'ShrinkOutlined', value: <Icons.ShrinkOutlined /> },
        { name: 'ArrowsAltOutlined', value: <Icons.ArrowsAltOutlined /> },

        { name: 'DownOutlined', value: <Icons.DownOutlined /> },
        { name: 'UpOutlined', value: <Icons.UpOutlined /> },
        { name: 'LeftOutlined', value: <Icons.LeftOutlined /> },
        { name: 'RightOutlined', value: <Icons.RightOutlined /> },
        { name: 'CaretUpOutlined', value: <Icons.CaretUpOutlined /> },
        { name: 'CaretDownOutlined', value: <Icons.CaretDownOutlined /> },

        { name: 'CaretLeftOutlined', value: <Icons.CaretLeftOutlined /> },
        { name: 'CaretRightOutlined', value: <Icons.CaretRightOutlined /> },
        { name: 'UpCircleOutlined', value: <Icons.UpCircleOutlined /> },
        { name: 'DownCircleOutlined', value: <Icons.DownCircleOutlined /> },
        { name: 'LeftCircleOutlined', value: <Icons.LeftCircleOutlined /> },
        { name: 'RightCircleOutlined', value: <Icons.RightCircleOutlined /> },

        { name: 'DoubleRightOutlined', value: <Icons.DoubleRightOutlined /> },
        { name: 'DoubleLeftOutlined', value: <Icons.DoubleLeftOutlined /> },
        { name: 'VerticalLeftOutlined', value: <Icons.VerticalLeftOutlined /> },
        { name: 'VerticalRightOutlined', value: <Icons.VerticalRightOutlined /> },
        { name: 'VerticalAlignTopOutlined', value: <Icons.VerticalAlignTopOutlined /> },
        { name: 'VerticalAlignMiddleOutlined', value: <Icons.VerticalAlignMiddleOutlined /> },

        { name: 'VerticalAlignBottomOutlined', value: <Icons.VerticalAlignBottomOutlined /> },
        { name: 'ForwardOutlined', value: <Icons.ForwardOutlined /> },
        { name: 'BackwardOutlined', value: <Icons.BackwardOutlined /> },
        { name: 'RollbackOutlined', value: <Icons.RollbackOutlined /> },
        { name: 'EnterOutlined', value: <Icons.EnterOutlined /> },
        { name: 'RetweetOutlined', value: <Icons.RetweetOutlined /> },

        { name: 'SwapOutlined', value: <Icons.SwapOutlined /> },
        { name: 'SwapLeftOutlined', value: <Icons.SwapLeftOutlined /> },
        { name: 'SwapRightOutlined', value: <Icons.SwapRightOutlined /> },
        { name: 'ArrowUpOutlined', value: <Icons.ArrowUpOutlined /> },
        { name: 'ArrowDownOutlined', value: <Icons.ArrowDownOutlined /> },
        { name: 'ArrowLeftOutlined', value: <Icons.ArrowLeftOutlined /> },

        { name: 'ArrowRightOutlined', value: <Icons.ArrowRightOutlined /> },
        { name: 'PlayCircleOutlined', value: <Icons.PlayCircleOutlined /> },
        { name: 'UpSquareOutlined', value: <Icons.UpSquareOutlined /> },
        { name: 'DownSquareOutlined', value: <Icons.DownSquareOutlined /> },
        { name: 'LeftSquareOutlined', value: <Icons.LeftSquareOutlined /> },
        { name: 'RightSquareOutlined', value: <Icons.RightSquareOutlined /> },

        { name: 'LoginOutlined', value: <Icons.LoginOutlined /> },
        { name: 'LogoutOutlined', value: <Icons.LogoutOutlined /> },
        { name: 'MenuFoldOutlined', value: <Icons.MenuFoldOutlined /> },
        { name: 'MenuUnfoldOutlined', value: <Icons.MenuUnfoldOutlined /> },
        { name: 'BorderBottomOutlined', value: <Icons.BorderBottomOutlined /> },
        { name: 'BorderHorizontalOutlined', value: <Icons.BorderHorizontalOutlined /> },

        { name: 'BorderInnerOutlined', value: <Icons.BorderInnerOutlined /> },
        { name: 'BorderOuterOutlined', value: <Icons.BorderOuterOutlined /> },
        { name: 'BorderLeftOutlined', value: <Icons.BorderLeftOutlined /> },
        { name: 'BorderRightOutlined', value: <Icons.BorderRightOutlined /> },
        { name: 'BorderTopOutlined', value: <Icons.BorderTopOutlined /> },
        { name: 'BorderVerticleOutlined', value: <Icons.BorderVerticleOutlined /> },

        { name: 'PicCenterOutlined', value: <Icons.PicCenterOutlined /> },
        { name: 'PicLeftOutlined', value: <Icons.PicLeftOutlined /> },
        { name: 'PicRightOutlined', value: <Icons.PicRightOutlined /> },
        { name: 'RadiusBottomleftOutlined', value: <Icons.RadiusBottomleftOutlined /> },
        { name: 'RadiusBottomrightOutlined', value: <Icons.RadiusBottomrightOutlined /> },
        { name: 'RadiusUpleftOutlined', value: <Icons.RadiusUpleftOutlined /> },

        { name: 'RadiusUprightOutlined', value: <Icons.RadiusUprightOutlined /> },
        { name: 'FullscreenOutlined', value: <Icons.FullscreenOutlined /> },
        { name: 'FullscreenExitOutlined', value: <Icons.FullscreenExitOutlined /> },
      ],
    },
    {
      name: 'tips',
      items: [
        { name: 'QuestionOutlined', value: <Icons.QuestionOutlined /> },
        { name: 'QuestionCircleOutlined', value: <Icons.QuestionCircleOutlined /> },
        { name: 'PlusOutlined', value: <Icons.PlusOutlined /> },
        { name: 'PlusCircleOutlined', value: <Icons.PlusCircleOutlined /> },
        { name: 'PauseOutlined', value: <Icons.PauseOutlined /> },
        { name: 'PauseCircleOutlined', value: <Icons.PauseCircleOutlined /> },

        { name: 'MinusOutlined', value: <Icons.MinusOutlined /> },
        { name: 'MinusCircleOutlined', value: <Icons.MinusCircleOutlined /> },
        { name: 'PlusSquareOutlined', value: <Icons.PlusSquareOutlined /> },
        { name: 'MinusSquareOutlined', value: <Icons.MinusSquareOutlined /> },
        { name: 'InfoOutlined', value: <Icons.InfoOutlined /> },
        { name: 'InfoCircleOutlined', value: <Icons.InfoCircleOutlined /> },

        { name: 'ExclamationOutlined', value: <Icons.ExclamationOutlined /> },
        { name: 'ExclamationCircleOutlined', value: <Icons.ExclamationCircleOutlined /> },
        { name: 'CloseOutlined', value: <Icons.CloseOutlined /> },
        { name: 'CloseCircleOutlined', value: <Icons.CloseCircleOutlined /> },
        { name: 'CloseSquareOutlined', value: <Icons.CloseSquareOutlined /> },
        { name: 'CheckOutlined', value: <Icons.CheckOutlined /> },

        { name: 'CheckCircleOutlined', value: <Icons.CheckCircleOutlined /> },
        { name: 'CheckSquareOutlined', value: <Icons.CheckSquareOutlined /> },
        { name: 'ClockCircleOutlined', value: <Icons.ClockCircleOutlined /> },
        { name: 'WarningOutlined', value: <Icons.WarningOutlined /> },
        { name: 'IssuesCloseOutlined', value: <Icons.IssuesCloseOutlined /> },
        { name: 'StopOutlined', value: <Icons.StopOutlined /> },
      ],
    },
    {
      name: 'edit',
      items: [
        { name: 'EditOutlined', value: <Icons.EditOutlined /> },
        { name: 'FormOutlined', value: <Icons.FormOutlined /> },
        { name: 'CopyOutlined', value: <Icons.CopyOutlined /> },
        { name: 'ScissorOutlined', value: <Icons.ScissorOutlined /> },
        { name: 'DeleteOutlined', value: <Icons.DeleteOutlined /> },
        { name: 'SnippetsOutlined', value: <Icons.SnippetsOutlined /> },

        { name: 'DiffOutlined', value: <Icons.DiffOutlined /> },
        { name: 'HighlightOutlined', value: <Icons.HighlightOutlined /> },
        { name: 'AlignCenterOutlined', value: <Icons.AlignCenterOutlined /> },
        { name: 'AlignLeftOutlined', value: <Icons.AlignLeftOutlined /> },
        { name: 'AlignRightOutlined', value: <Icons.AlignRightOutlined /> },
        { name: 'BgColorsOutlined', value: <Icons.BgColorsOutlined /> },

        { name: 'BoldOutlined', value: <Icons.BoldOutlined /> },
        { name: 'ItalicOutlined', value: <Icons.ItalicOutlined /> },
        { name: 'UnderlineOutlined', value: <Icons.UnderlineOutlined /> },
        { name: 'StrikethroughOutlined', value: <Icons.StrikethroughOutlined /> },
        { name: 'RedoOutlined', value: <Icons.RedoOutlined /> },
        { name: 'UndoOutlined', value: <Icons.UndoOutlined /> },

        { name: 'ZoomInOutlined', value: <Icons.ZoomInOutlined /> },
        { name: 'ZoomOutOutlined', value: <Icons.ZoomOutOutlined /> },
        { name: 'FontColorsOutlined', value: <Icons.FontColorsOutlined /> },
        { name: 'FontSizeOutlined', value: <Icons.FontSizeOutlined /> },
        { name: 'LineHeightOutlined', value: <Icons.LineHeightOutlined /> },
        { name: 'DashOutlined', value: <Icons.DashOutlined /> },

        { name: 'SmallDashOutlined', value: <Icons.SmallDashOutlined /> },
        { name: 'SortAscendingOutlined', value: <Icons.SortAscendingOutlined /> },
        { name: 'SortDescendingOutlined', value: <Icons.SortDescendingOutlined /> },
        { name: 'DragOutlined', value: <Icons.DragOutlined /> },
        { name: 'OrderedListOutlined', value: <Icons.OrderedListOutlined /> },
        { name: 'UnorderedListOutlined', value: <Icons.UnorderedListOutlined /> },

        { name: 'RadiusSettingOutlined', value: <Icons.RadiusSettingOutlined /> },
        { name: 'ColumnWidthOutlined', value: <Icons.ColumnWidthOutlined /> },
        { name: 'ColumnHeightOutlined', value: <Icons.ColumnHeightOutlined /> },
      ],
    },
    {
      name: 'chart',
      items: [
        { name: 'AreaChartOutlined', value: <Icons.AreaChartOutlined /> },
        { name: 'PieChartOutlined', value: <Icons.PieChartOutlined /> },
        { name: 'BarChartOutlined', value: <Icons.BarChartOutlined /> },
        { name: 'DotChartOutlined', value: <Icons.DotChartOutlined /> },
        { name: 'LineChartOutlined', value: <Icons.LineChartOutlined /> },
        { name: 'RadarChartOutlined', value: <Icons.RadarChartOutlined /> },

        { name: 'HeatMapOutlined', value: <Icons.HeatMapOutlined /> },
        { name: 'FallOutlined', value: <Icons.FallOutlined /> },
        { name: 'RiseOutlined', value: <Icons.RiseOutlined /> },
        { name: 'StockOutlined', value: <Icons.StockOutlined /> },
        { name: 'BoxPlotOutlined', value: <Icons.BoxPlotOutlined /> },
        { name: 'FundOutlined', value: <Icons.FundOutlined /> },

        { name: 'SlidersOutlined', value: <Icons.SlidersOutlined /> },
      ],
    },
    {
      name: 'brand',
      items: [
        { name: 'AndroidOutlined', value: <Icons.AndroidOutlined /> },
        { name: 'AppleOutlined', value: <Icons.AppleOutlined /> },
        { name: 'WindowsOutlined', value: <Icons.WindowsOutlined /> },
        { name: 'IeOutlined', value: <Icons.IeOutlined /> },
        { name: 'ChromeOutlined', value: <Icons.ChromeOutlined /> },
        { name: 'GithubOutlined', value: <Icons.GithubOutlined /> },

        { name: 'AliwangwangOutlined', value: <Icons.AliwangwangOutlined /> },
        { name: 'DingdingOutlined', value: <Icons.DingdingOutlined /> },
        { name: 'WeiboSquareOutlined', value: <Icons.WeiboSquareOutlined /> },
        { name: 'WeiboCircleOutlined', value: <Icons.WeiboCircleOutlined /> },
        { name: 'TaobaoCircleOutlined', value: <Icons.TaobaoCircleOutlined /> },
        { name: 'Html5Outlined', value: <Icons.Html5Outlined /> },

        { name: 'WeiboOutlined', value: <Icons.WeiboOutlined /> },
        { name: 'TwitterOutlined', value: <Icons.TwitterOutlined /> },
        { name: 'WechatOutlined', value: <Icons.WechatOutlined /> },
        { name: 'YoutubeOutlined', value: <Icons.YoutubeOutlined /> },
        { name: 'AlipayCircleOutlined', value: <Icons.AlipayCircleOutlined /> },
        { name: 'TaobaoOutlined', value: <Icons.TaobaoOutlined /> },

        { name: 'SkypeOutlined', value: <Icons.SkypeOutlined /> },
        { name: 'QqOutlined', value: <Icons.QqOutlined /> },
        { name: 'MediumWorkmarkOutlined', value: <Icons.MediumWorkmarkOutlined /> },
        { name: 'GitlabOutlined', value: <Icons.GitlabOutlined /> },
        { name: 'MediumOutlined', value: <Icons.MediumOutlined /> },
        { name: 'LinkedinOutlined', value: <Icons.LinkedinOutlined /> },

        { name: 'GooglePlusOutlined', value: <Icons.GooglePlusOutlined /> },
        { name: 'DropboxOutlined', value: <Icons.DropboxOutlined /> },
        { name: 'FacebookOutlined', value: <Icons.FacebookOutlined /> },
        { name: 'CodepenOutlined', value: <Icons.CodepenOutlined /> },
        { name: 'CodeSandboxOutlined', value: <Icons.CodeSandboxOutlined /> },
        { name: 'AmazonOutlined', value: <Icons.AmazonOutlined /> },

        { name: 'GoogleOutlined', value: <Icons.GoogleOutlined /> },
        { name: 'CodepenCircleOutlined', value: <Icons.CodepenCircleOutlined /> },
        { name: 'AlipayOutlined', value: <Icons.AlipayOutlined /> },
        { name: 'AntDesignOutlined', value: <Icons.AntDesignOutlined /> },
        { name: 'AntCloudOutlined', value: <Icons.AntCloudOutlined /> },
        { name: 'AliyunOutlined', value: <Icons.AliyunOutlined /> },

        { name: 'ZhihuOutlined', value: <Icons.ZhihuOutlined /> },
        { name: 'SlackOutlined', value: <Icons.SlackOutlined /> },
        { name: 'SlackSquareOutlined', value: <Icons.SlackSquareOutlined /> },
        { name: 'BehanceOutlined', value: <Icons.BehanceOutlined /> },
        { name: 'BehanceSquareOutlined', value: <Icons.BehanceSquareOutlined /> },
        { name: 'DribbbleOutlined', value: <Icons.DribbbleOutlined /> },

        { name: 'DribbbleSquareOutlined', value: <Icons.DribbbleSquareOutlined /> },
        { name: 'InstagramOutlined', value: <Icons.InstagramOutlined /> },
        { name: 'YuqueOutlined', value: <Icons.YuqueOutlined /> },
        { name: 'AlibabaOutlined', value: <Icons.AlibabaOutlined /> },
        { name: 'YahooOutlined', value: <Icons.YahooOutlined /> },
        { name: 'RedditOutlined', value: <Icons.RedditOutlined /> },

        { name: 'SketchOutlined', value: <Icons.SketchOutlined /> },
      ],
    },
    {
      name: 'web',
      items: [
        { name: 'AccountBookOutlined', value: <Icons.AccountBookOutlined /> },
        { name: 'AimOutlined', value: <Icons.AimOutlined /> },
        { name: 'AlertOutlined', value: <Icons.AlertOutlined /> },
        { name: 'ApartmentOutlined', value: <Icons.ApartmentOutlined /> },
        { name: 'ApiOutlined', value: <Icons.ApiOutlined /> },
        { name: 'AppstoreAddOutlined', value: <Icons.AppstoreAddOutlined /> },

        { name: 'AppstoreOutlined', value: <Icons.AppstoreOutlined /> },
        { name: 'AudioOutlined', value: <Icons.AudioOutlined /> },
        { name: 'AudioMutedOutlined', value: <Icons.AudioMutedOutlined /> },
        { name: 'AuditOutlined', value: <Icons.AuditOutlined /> },
        { name: 'BankOutlined', value: <Icons.BankOutlined /> },
        { name: 'BarcodeOutlined', value: <Icons.BarcodeOutlined /> },

        { name: 'BarsOutlined', value: <Icons.BarsOutlined /> },
        { name: 'BellOutlined', value: <Icons.BellOutlined /> },
        { name: 'BlockOutlined', value: <Icons.BlockOutlined /> },
        { name: 'BookOutlined', value: <Icons.BookOutlined /> },
        { name: 'BorderOutlined', value: <Icons.BorderOutlined /> },
        { name: 'BorderlessTableOutlined', value: <Icons.BorderlessTableOutlined /> },

        { name: 'BranchesOutlined', value: <Icons.BranchesOutlined /> },
        { name: 'BugOutlined', value: <Icons.BugOutlined /> },
        { name: 'BuildOutlined', value: <Icons.BuildOutlined /> },
        { name: 'BulbOutlined', value: <Icons.BulbOutlined /> },
        { name: 'CalculatorOutlined', value: <Icons.CalculatorOutlined /> },
        { name: 'CalendarOutlined', value: <Icons.CalendarOutlined /> },

        { name: 'CameraOutlined', value: <Icons.CameraOutlined /> },
        { name: 'CarOutlined', value: <Icons.CarOutlined /> },
        { name: 'CarryOutOutlined', value: <Icons.CarryOutOutlined /> },
        { name: 'CiCircleOutlined', value: <Icons.CiCircleOutlined /> },
        { name: 'CiOutlined', value: <Icons.CiOutlined /> },
        { name: 'ClearOutlined', value: <Icons.ClearOutlined /> },

        { name: 'CloudDownloadOutlined', value: <Icons.CloudDownloadOutlined /> },
        { name: 'CloudOutlined', value: <Icons.CloudOutlined /> },
        { name: 'CloudServerOutlined', value: <Icons.CloudServerOutlined /> },
        { name: 'CloudSyncOutlined', value: <Icons.CloudSyncOutlined /> },
        { name: 'CloudUploadOutlined', value: <Icons.CloudUploadOutlined /> },
        { name: 'ClusterOutlined', value: <Icons.ClusterOutlined /> },

        { name: 'CodeOutlined', value: <Icons.CodeOutlined /> },
        { name: 'CoffeeOutlined', value: <Icons.CoffeeOutlined /> },
        { name: 'CommentOutlined', value: <Icons.CommentOutlined /> },
        { name: 'CompassOutlined', value: <Icons.CompassOutlined /> },
        { name: 'CompressOutlined', value: <Icons.CompressOutlined /> },
        { name: 'ConsoleSqlOutlined', value: <Icons.ConsoleSqlOutlined /> },

        { name: 'ContactsOutlined', value: <Icons.ContactsOutlined /> },
        { name: 'ContainerOutlined', value: <Icons.ContainerOutlined /> },
        { name: 'ControlOutlined', value: <Icons.ControlOutlined /> },
        { name: 'CopyrightOutlined', value: <Icons.CopyrightOutlined /> },
        { name: 'CreditCardOutlined', value: <Icons.CreditCardOutlined /> },
        { name: 'CrownOutlined', value: <Icons.CrownOutlined /> },

        { name: 'CustomerServiceOutlined', value: <Icons.CustomerServiceOutlined /> },
        { name: 'DashboardOutlined', value: <Icons.DashboardOutlined /> },
        { name: 'DatabaseOutlined', value: <Icons.DatabaseOutlined /> },
        { name: 'DeleteColumnOutlined', value: <Icons.DeleteColumnOutlined /> },
        { name: 'DeleteRowOutlined', value: <Icons.DeleteRowOutlined /> },
        { name: 'DeliveredProcedureOutlined', value: <Icons.DeliveredProcedureOutlined /> },

        { name: 'DeploymentUnitOutlined', value: <Icons.DeploymentUnitOutlined /> },
        { name: 'DesktopOutlined', value: <Icons.DesktopOutlined /> },
        { name: 'DingtalkOutlined', value: <Icons.DingtalkOutlined /> },
        { name: 'DisconnectOutlined', value: <Icons.DisconnectOutlined /> },
        { name: 'DislikeOutlined', value: <Icons.DislikeOutlined /> },
        { name: 'DollarCircleOutlined', value: <Icons.DollarCircleOutlined /> },

        { name: 'DollarOutlined', value: <Icons.DollarOutlined /> },
        { name: 'DownloadOutlined', value: <Icons.DownloadOutlined /> },
        { name: 'EllipsisOutlined', value: <Icons.EllipsisOutlined /> },
        { name: 'EnvironmentOutlined', value: <Icons.EnvironmentOutlined /> },
        { name: 'EuroCircleOutlined', value: <Icons.EuroCircleOutlined /> },
        { name: 'EuroOutlined', value: <Icons.EuroOutlined /> },

        { name: 'ExceptionOutlined', value: <Icons.ExceptionOutlined /> },
        { name: 'ExpandAltOutlined', value: <Icons.ExpandAltOutlined /> },
        { name: 'ExpandOutlined', value: <Icons.ExpandOutlined /> },
        { name: 'ExperimentOutlined', value: <Icons.ExperimentOutlined /> },
        { name: 'ExportOutlined', value: <Icons.ExportOutlined /> },
        { name: 'EyeOutlined', value: <Icons.EyeOutlined /> },

        { name: 'EyeInvisibleOutlined', value: <Icons.EyeInvisibleOutlined /> },
        { name: 'FieldBinaryOutlined', value: <Icons.FieldBinaryOutlined /> },
        { name: 'FieldNumberOutlined', value: <Icons.FieldNumberOutlined /> },
        { name: 'FieldStringOutlined', value: <Icons.FieldStringOutlined /> },
        { name: 'FieldTimeOutlined', value: <Icons.FieldTimeOutlined /> },
        { name: 'FileAddOutlined', value: <Icons.FileAddOutlined /> },

        { name: 'FileDoneOutlined', value: <Icons.FileDoneOutlined /> },
        { name: 'FileExcelOutlined', value: <Icons.FileExcelOutlined /> },
        { name: 'FileExclamationOutlined', value: <Icons.FileExclamationOutlined /> },
        { name: 'FileOutlined', value: <Icons.FileOutlined /> },
        { name: 'FileGifOutlined', value: <Icons.FileGifOutlined /> },
        { name: 'FileImageOutlined', value: <Icons.FileImageOutlined /> },

        { name: 'FileJpgOutlined', value: <Icons.FileJpgOutlined /> },
        { name: 'FileMarkdownOutlined', value: <Icons.FileMarkdownOutlined /> },
        { name: 'FilePdfOutlined', value: <Icons.FilePdfOutlined /> },
        { name: 'FilePptOutlined', value: <Icons.FilePptOutlined /> },
        { name: 'FileProtectOutlined', value: <Icons.FileProtectOutlined /> },
        { name: 'FileSearchOutlined', value: <Icons.FileSearchOutlined /> },

        { name: 'FileSyncOutlined', value: <Icons.FileSyncOutlined /> },
        { name: 'FileTextOutlined', value: <Icons.FileTextOutlined /> },
        { name: 'FileUnknownOutlined', value: <Icons.FileUnknownOutlined /> },
        { name: 'FileWordOutlined', value: <Icons.FileWordOutlined /> },
        { name: 'FileZipOutlined', value: <Icons.FileZipOutlined /> },
        { name: 'FilterOutlined', value: <Icons.FilterOutlined /> },


        { name: 'FireOutlined', value: <Icons.FireOutlined /> },
        { name: 'FlagOutlined', value: <Icons.FlagOutlined /> },
        { name: 'FolderAddOutlined', value: <Icons.FolderAddOutlined /> },
        { name: 'FolderOutlined', value: <Icons.FolderOutlined /> },
        { name: 'FolderOpenOutlined', value: <Icons.FolderOpenOutlined /> },
        { name: 'FolderViewOutlined', value: <Icons.FolderViewOutlined /> },

        { name: 'ForkOutlined', value: <Icons.ForkOutlined /> },
        { name: 'FormatPainterOutlined', value: <Icons.FormatPainterOutlined /> },
        { name: 'FrownOutlined', value: <Icons.FrownOutlined /> },
        { name: 'FunctionOutlined', value: <Icons.FunctionOutlined /> },
        { name: 'FundProjectionScreenOutlined', value: <Icons.FundProjectionScreenOutlined /> },
        { name: 'FundViewOutlined', value: <Icons.FundViewOutlined /> },

        { name: 'FunnelPlotOutlined', value: <Icons.FunnelPlotOutlined /> },
        { name: 'GatewayOutlined', value: <Icons.GatewayOutlined /> },
        { name: 'GifOutlined', value: <Icons.GifOutlined /> },
        { name: 'GiftOutlined', value: <Icons.GiftOutlined /> },
        { name: 'GlobalOutlined', value: <Icons.GlobalOutlined /> },
        { name: 'GoldOutlined', value: <Icons.GoldOutlined /> },

        { name: 'GroupOutlined', value: <Icons.GroupOutlined /> },
        { name: 'HddOutlined', value: <Icons.HddOutlined /> },
        { name: 'HeartOutlined', value: <Icons.HeartOutlined /> },
        { name: 'HistoryOutlined', value: <Icons.HistoryOutlined /> },
        { name: 'HolderOutlined', value: <Icons.HolderOutlined /> },
        { name: 'HomeOutlined', value: <Icons.HomeOutlined /> },

        { name: 'HourglassOutlined', value: <Icons.HourglassOutlined /> },
        { name: 'IdcardOutlined', value: <Icons.IdcardOutlined /> },
        { name: 'ImportOutlined', value: <Icons.ImportOutlined /> },
        { name: 'InboxOutlined', value: <Icons.InboxOutlined /> },
        { name: 'InsertRowAboveOutlined', value: <Icons.InsertRowAboveOutlined /> },
        { name: 'InsertRowBelowOutlined', value: <Icons.InsertRowBelowOutlined /> },

        { name: 'InsertRowLeftOutlined', value: <Icons.InsertRowLeftOutlined /> },
        { name: 'InsertRowRightOutlined', value: <Icons.InsertRowRightOutlined /> },
        { name: 'InsuranceOutlined', value: <Icons.InsuranceOutlined /> },
        { name: 'InteractionOutlined', value: <Icons.InteractionOutlined /> },
        { name: 'KeyOutlined', value: <Icons.KeyOutlined /> },
        { name: 'LaptopOutlined', value: <Icons.LaptopOutlined /> },

        { name: 'LayoutOutlined', value: <Icons.LayoutOutlined /> },
        { name: 'LikeOutlined', value: <Icons.LikeOutlined /> },
        { name: 'LineOutlined', value: <Icons.LineOutlined /> },
        { name: 'LinkOutlined', value: <Icons.LinkOutlined /> },
        { name: 'Loading3QuartersOutlined', value: <Icons.Loading3QuartersOutlined /> },
        { name: 'LoadingOutlined', value: <Icons.LoadingOutlined /> },

        { name: 'LockOutlined', value: <Icons.LockOutlined /> },
        { name: 'MacCommandOutlined', value: <Icons.MacCommandOutlined /> },
        { name: 'MailOutlined', value: <Icons.MailOutlined /> },
        { name: 'ManOutlined', value: <Icons.ManOutlined /> },
        { name: 'MedicineBoxOutlined', value: <Icons.MedicineBoxOutlined /> },
        { name: 'MehOutlined', value: <Icons.MehOutlined /> },

        { name: 'MenuOutlined', value: <Icons.MenuOutlined /> },
        { name: 'MergeCellsOutlined', value: <Icons.MergeCellsOutlined /> },
        { name: 'MessageOutlined', value: <Icons.MessageOutlined /> },
        { name: 'MobileOutlined', value: <Icons.MobileOutlined /> },
        { name: 'MoneyCollectOutlined', value: <Icons.MoneyCollectOutlined /> },
        { name: 'MonitorOutlined', value: <Icons.MonitorOutlined /> },

        { name: 'MoreOutlined', value: <Icons.MoreOutlined /> },
        { name: 'NodeCollapseOutlined', value: <Icons.NodeCollapseOutlined /> },
        { name: 'NodeExpandOutlined', value: <Icons.NodeExpandOutlined /> },
        { name: 'NodeIndexOutlined', value: <Icons.NodeIndexOutlined /> },
        { name: 'NotificationOutlined', value: <Icons.NotificationOutlined /> },
        { name: 'NumberOutlined', value: <Icons.NumberOutlined /> },

        { name: 'OneToOneOutlined', value: <Icons.OneToOneOutlined /> },
        { name: 'PaperClipOutlined', value: <Icons.PaperClipOutlined /> },
        { name: 'PartitionOutlined', value: <Icons.PartitionOutlined /> },
        { name: 'PayCircleOutlined', value: <Icons.PayCircleOutlined /> },
        { name: 'PercentageOutlined', value: <Icons.PercentageOutlined /> },
        { name: 'PhoneOutlined', value: <Icons.PhoneOutlined /> },

        { name: 'PictureOutlined', value: <Icons.PictureOutlined /> },
        { name: 'PlaySquareOutlined', value: <Icons.PlaySquareOutlined /> },
        { name: 'PoundCircleOutlined', value: <Icons.PoundCircleOutlined /> },
        { name: 'PoundOutlined', value: <Icons.PoundOutlined /> },
        { name: 'PoweroffOutlined', value: <Icons.PoweroffOutlined /> },
        { name: 'PrinterOutlined', value: <Icons.PrinterOutlined /> },

        { name: 'ProfileOutlined', value: <Icons.ProfileOutlined /> },
        { name: 'ProjectOutlined', value: <Icons.ProjectOutlined /> },
        { name: 'PropertySafetyOutlined', value: <Icons.PropertySafetyOutlined /> },
        { name: 'PullRequestOutlined', value: <Icons.PullRequestOutlined /> },
        { name: 'PushpinOutlined', value: <Icons.PushpinOutlined /> },
        { name: 'QrcodeOutlined', value: <Icons.QrcodeOutlined /> },

        { name: 'ReadOutlined', value: <Icons.ReadOutlined /> },
        { name: 'ReconciliationOutlined', value: <Icons.ReconciliationOutlined /> },
        { name: 'RedEnvelopeOutlined', value: <Icons.RedEnvelopeOutlined /> },
        { name: 'ReloadOutlined', value: <Icons.ReloadOutlined /> },
        { name: 'RestOutlined', value: <Icons.RestOutlined /> },
        { name: 'RobotOutlined', value: <Icons.RobotOutlined /> },

        { name: 'RocketOutlined', value: <Icons.RocketOutlined /> },
        { name: 'RotateLeftOutlined', value: <Icons.RotateLeftOutlined /> },
        { name: 'RotateRightOutlined', value: <Icons.RotateRightOutlined /> },
        { name: 'SafetyCertificateOutlined', value: <Icons.SafetyCertificateOutlined /> },
        { name: 'SafetyOutlined', value: <Icons.SafetyOutlined /> },
        { name: 'SaveOutlined', value: <Icons.SaveOutlined /> },

        { name: 'ScanOutlined', value: <Icons.ScanOutlined /> },
        { name: 'ScheduleOutlined', value: <Icons.ScheduleOutlined /> },
        { name: 'SearchOutlined', value: <Icons.SearchOutlined /> },
        { name: 'SecurityScanOutlined', value: <Icons.SecurityScanOutlined /> },
        { name: 'SelectOutlined', value: <Icons.SelectOutlined /> },
        { name: 'SendOutlined', value: <Icons.SendOutlined /> },

        { name: 'SettingOutlined', value: <Icons.SettingOutlined /> },
        { name: 'ShakeOutlined', value: <Icons.ShakeOutlined /> },
        { name: 'ShareAltOutlined', value: <Icons.ShareAltOutlined /> },
        { name: 'ShopOutlined', value: <Icons.ShopOutlined /> },
        { name: 'ShoppingCartOutlined', value: <Icons.ShoppingCartOutlined /> },
        { name: 'ShoppingOutlined', value: <Icons.ShoppingOutlined /> },

        { name: 'SisternodeOutlined', value: <Icons.SisternodeOutlined /> },
        { name: 'SkinOutlined', value: <Icons.SkinOutlined /> },
        { name: 'SmileOutlined', value: <Icons.SmileOutlined /> },
        { name: 'SolutionOutlined', value: <Icons.SolutionOutlined /> },
        { name: 'SoundOutlined', value: <Icons.SoundOutlined /> },
        { name: 'SplitCellsOutlined', value: <Icons.SplitCellsOutlined /> },

        { name: 'StarOutlined', value: <Icons.StarOutlined /> },
        { name: 'SubnodeOutlined', value: <Icons.SubnodeOutlined /> },
        { name: 'SwitcherOutlined', value: <Icons.SwitcherOutlined /> },
        { name: 'SyncOutlined', value: <Icons.SyncOutlined /> },
        { name: 'TableOutlined', value: <Icons.TableOutlined /> },
        { name: 'TabletOutlined', value: <Icons.TabletOutlined /> },

        { name: 'TagOutlined', value: <Icons.TagOutlined /> },
        { name: 'TagsOutlined', value: <Icons.TagsOutlined /> },
        { name: 'TeamOutlined', value: <Icons.TeamOutlined /> },
        { name: 'ThunderboltOutlined', value: <Icons.ThunderboltOutlined /> },
        { name: 'ToTopOutlined', value: <Icons.ToTopOutlined /> },
        { name: 'ToolOutlined', value: <Icons.ToolOutlined /> },

        { name: 'TrademarkCircleOutlined', value: <Icons.TrademarkCircleOutlined /> },
        { name: 'TrademarkOutlined', value: <Icons.TrademarkOutlined /> },
        { name: 'TransactionOutlined', value: <Icons.TransactionOutlined /> },
        { name: 'TranslationOutlined', value: <Icons.TranslationOutlined /> },
        { name: 'TrophyOutlined', value: <Icons.TrophyOutlined /> },
        { name: 'UngroupOutlined', value: <Icons.UngroupOutlined /> },

        { name: 'UnlockOutlined', value: <Icons.UnlockOutlined /> },
        { name: 'UploadOutlined', value: <Icons.UploadOutlined /> },
        { name: 'UsbOutlined', value: <Icons.UsbOutlined /> },
        { name: 'UserAddOutlined', value: <Icons.UserAddOutlined /> },
        { name: 'UserDeleteOutlined', value: <Icons.UserDeleteOutlined /> },
        { name: 'UserOutlined', value: <Icons.UserOutlined /> },

        { name: 'UserSwitchOutlined', value: <Icons.UserSwitchOutlined /> },
        { name: 'UsergroupAddOutlined', value: <Icons.UsergroupAddOutlined /> },
        { name: 'UsergroupDeleteOutlined', value: <Icons.UsergroupDeleteOutlined /> },
        { name: 'VerifiedOutlined', value: <Icons.VerifiedOutlined /> },
        { name: 'VideoCameraAddOutlined', value: <Icons.VideoCameraAddOutlined /> },
        { name: 'VideoCameraOutlined', value: <Icons.VideoCameraOutlined /> },

        { name: 'WalletOutlined', value: <Icons.WalletOutlined /> },
        { name: 'WhatsAppOutlined', value: <Icons.WhatsAppOutlined /> },
        { name: 'WifiOutlined', value: <Icons.WifiOutlined /> },
        { name: 'WomanOutlined', value: <Icons.WomanOutlined /> },
      ],
    },
  ],
}

export default linear